dependencies {
    compileOnly(libs.jetbrains.annotations)

    modClientLocalRuntime(forge.jecharacters.get())

    // Mixin (& Extras)
    annotationProcessor(variantOf(libs.mixin) { classifier("processor") })
    api(annotationProcessor(forge.mixinExtras.common.get()))
    // Recipe Viewers
    modCompileOnly(forge.bundles.jei)
    modCompileOnly(forge.emi)

    // Mekanism
    modCompileOnly(forge.mekanism)
    modCompileOnly(variantOf(forge.mekanism) { classifier("additions") })
    modCompileOnly(variantOf(forge.mekanism) { classifier("generators") })
    modCompileOnly(variantOf(forge.mekanism) { classifier("tools") })

    // Compatibility
    modCompileOnly(forge.allthemodium)
    localRuntime(forge.allthemodium)
    modCompileOnly(forge.alltheores)
    localRuntime(forge.alltheores)

    // WAILA-likes
    modCompileOnly(forge.jade)

    // Mekanism
    modLocalRuntime(forge.mekanism)
    modLocalRuntime(variantOf(forge.mekanism) { classifier("additions") })
    modLocalRuntime(variantOf(forge.mekanism) { classifier("generators") })
    modLocalRuntime(variantOf(forge.mekanism) { classifier("tools") })

    // Standard runtime mods //
    modLocalRuntime(forge.geckolib)
    modLocalRuntime(forge.alltheores)
    modLocalRuntime(forge.allthemodium)
    modLocalRuntime(forge.jade)
    modLocalRuntime(forge.modernfix)
    modLocalRuntime(forge.ferritecore)

    // Runtime Recipe Viewers - uncomment whichever one you want to use //
//    modLocalRuntime(forge.emi)
    modLocalRuntime(forge.jei.forge.impl)

    // Client-only runtime mods //
    modClientLocalRuntime(forge.embeddium)
    modClientLocalRuntime(forge.oculus)
    modClientLocalRuntime(forge.modernui)
//    modClientLocalRuntime(forge.imblocker)
    renderNurseCfg(libs.renderNurse)

//    // Mouse Tweaks
//    modRuntimeOnly("curse.maven:mouse-tweaks-60089:5338457")

}