org.gradle.jvmargs = -Xmx6G
org.gradle.java.installations.auto-download=false
org.gradle.parallel = true
org.gradle.caching = true

mod_id = mekanismscience
mod_name = Mekanism: Science
mod_version = 1.0
mod_license = MIT
mod_description = A mod that adds more science elements to Mekanism.
mod_authors = FixedDolphin927, code-onigiri
mod_url =
mod_issue_tracker =
maven_group = com.fxd927.mekanismscience